version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: listmonk_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=listmonk
      - POSTGRES_PASSWORD=listmonk_pass
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    volumes:
      - listmonk_db_data:/var/lib/postgresql/data

  app:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    ports:
      - "9000:9000"
    environment:
      - TZ=America/Sao_Paulo
      - LISTMONK_db_host=db
      - LISTMONK_db_user=listmonk
      - LISTMONK_db_password=listmonk_pass
      - LISTMONK_db_name=listmonk
      - LISTMONK_db_port=5432
      - LISTMONK_db_ssl_mode=disable
      - LISTMONK_app_address=0.0.0.0:9000
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./uploads:/listmonk/uploads

  redis:
    image: redis:alpine
    container_name: zehla_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  listmonk_db_data:
