// =============================================================================
// ZEHLA SmartHotel — Dados Mock para Prospecção de Leads (Lessie AI)
// Dados realistas de pousadas brasileiras para desenvolvimento e demonstração
// =============================================================================

import type {
  Lead,
  Target,
  SwipeTemplate,
  Campaign,
  AgentLog,
  RouterProvider,
  BudgetGuardState,
} from './leads-types';

// ---------------------------------------------------------------------------
// Targets — Pousadas e hotéis independentes mapeados para prospecção
// ---------------------------------------------------------------------------
export const mockTargets: Target[] = [
  {
    id: 'tgt-001',
    name: 'Pousada Serenity',
    domain: 'pousadaserenity.com.br',
    website: 'https://www.pousadaserenity.com.br',
    city: 'Tiradentes',
    state: 'MG',
    status: 'active',
    priority: 92,
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-15T14:30:00Z',
  },
  {
    id: 'tgt-002',
    name: 'Casa da Montanha',
    domain: 'casadamontanha.com.br',
    website: 'https://www.casadamontanha.com.br',
    city: 'Gramado',
    state: 'RS',
    status: 'active',
    priority: 88,
    createdAt: '2025-06-02T09:15:00Z',
    updatedAt: '2025-06-14T11:20:00Z',
  },
  {
    id: 'tgt-003',
    name: 'Hotel Fazenda Vila Rica',
    domain: 'vilacafazenda.com.br',
    website: 'https://www.vilacafazenda.com.br',
    city: 'Ouro Preto',
    state: 'MG',
    status: 'prospected',
    priority: 75,
    createdAt: '2025-05-28T16:45:00Z',
    updatedAt: '2025-06-12T08:00:00Z',
  },
  {
    id: 'tgt-004',
    name: 'Pousada do Caminho',
    domain: 'pousadadocaminho.com.br',
    website: 'https://www.pousadadocaminho.com.br',
    city: 'Campos do Jordão',
    state: 'SP',
    status: 'active',
    priority: 85,
    createdAt: '2025-06-03T13:30:00Z',
    updatedAt: '2025-06-15T09:45:00Z',
  },
  {
    id: 'tgt-005',
    name: 'Solar do Vale',
    domain: 'solardovale.com.br',
    website: 'https://solardovale.com.br',
    city: 'Canela',
    state: 'RS',
    status: 'active',
    priority: 80,
    createdAt: '2025-06-04T11:00:00Z',
    updatedAt: '2025-06-13T16:10:00Z',
  },
  {
    id: 'tgt-006',
    name: 'Refúgio da Serra',
    domain: 'refugiodaserra.com.br',
    website: null,
    city: 'Paraty',
    state: 'RJ',
    status: 'pending',
    priority: 70,
    createdAt: '2025-06-05T08:20:00Z',
    updatedAt: '2025-06-10T12:00:00Z',
  },
  {
    id: 'tgt-007',
    name: 'Pousada Araras',
    domain: 'pousadaararas.com.br',
    website: 'https://www.pousadaararas.com.br',
    city: 'Jericoacoara',
    state: 'CE',
    status: 'inactive',
    priority: 45,
    createdAt: '2025-05-20T14:00:00Z',
    updatedAt: '2025-06-01T10:30:00Z',
  },
  {
    id: 'tgt-008',
    name: 'Laguna Beach Lodge',
    domain: 'lagunabeachlodge.com.br',
    website: 'https://lagunabeachlodge.com.br',
    city: 'Florianópolis',
    state: 'SC',
    status: 'active',
    priority: 90,
    createdAt: '2025-06-06T07:45:00Z',
    updatedAt: '2025-06-15T18:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Leads — Decisores identificados pela Lessie AI
// ---------------------------------------------------------------------------
export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    empresa: 'Pousada Serenity',
    decisor: 'Marina Albuquerque',
    cargo: 'Proprietária',
    email: 'marina@pousadaserenity.com.br',
    whatsapp: '5532999123456',
    setor: 'Hospedagem — Pousada Boutique',
    socialMedia: {
      instagram: '@pousadaserenity',
      facebook: 'Pousada Serenity Tiradentes',
      google: 'Pousada Serenity — Avaliação 4.8',
    },
    porte: 'pequeno',
    status: 'contacted',
    hook: 'Diagnóstico IDP mostrou gap de 32% no preço médio da alta temporada vs concorrentes locais',
    validationScore: 94,
    socialFootprint: {
      instagramSeguidores: 12400,
      googleReviews: 387,
      avgRating: 4.8,
      lastPostDate: '2025-06-14',
      responseRate: '92%',
    },
    metadata: {
      cnpj: '23.456.789/0001-01',
      quartos: 12,
      taxaOcupacao: 0.78,
      precoMedio: 380,
      canalPrincipal: 'Booking.com',
    },
    targetId: 'tgt-001',
    createdAt: '2025-06-10T08:00:00Z',
    updatedAt: '2025-06-15T14:30:00Z',
  },
  {
    id: 'lead-002',
    empresa: 'Casa da Montanha',
    decisor: 'Ricardo Hoffmann',
    cargo: 'Gerente Geral',
    email: 'ricardo@casadamontanha.com.br',
    whatsapp: '5554999876543',
    setor: 'Hospedagem — Hotel de Montanha',
    socialMedia: {
      instagram: '@casadamontanha.gramado',
      google: 'Casa da Montanha — Avaliação 4.6',
    },
    porte: 'medio',
    status: 'verified',
    hook: 'Preço médio 28% abaixo da média de Gramado na baixa temporada — oportunidade de yield',
    validationScore: 88,
    socialFootprint: {
      instagramSeguidores: 8900,
      googleReviews: 542,
      avgRating: 4.6,
      responseRate: '88%',
    },
    metadata: {
      cnpj: '15.789.012/0001-34',
      quartos: 24,
      taxaOcupacao: 0.72,
      precoMedio: 450,
      canalPrincipal: 'Direto + Booking',
    },
    targetId: 'tgt-002',
    createdAt: '2025-06-11T09:30:00Z',
    updatedAt: '2025-06-14T16:45:00Z',
  },
  {
    id: 'lead-003',
    empresa: 'Hotel Fazenda Vila Rica',
    decisor: 'Antônio Ferreira',
    cargo: 'Proprietário',
    email: 'antonio@vilacafazenda.com.br',
    whatsapp: '5531999765432',
    setor: 'Hospedagem — Hotel Fazenda',
    socialMedia: {
      instagram: '@vilacafazenda',
      facebook: 'Hotel Fazenda Vila Rica',
    },
    porte: 'grande',
    status: 'converted',
    hook: 'Receita potencial de R$ 180k/mês vs atual de R$ 112k — gap de 38% identificado',
    validationScore: 97,
    socialFootprint: {
      instagramSeguidores: 22300,
      googleReviews: 891,
      avgRating: 4.7,
      lastPostDate: '2025-06-15',
      responseRate: '95%',
    },
    metadata: {
      cnpj: '18.234.567/0001-56',
      quartos: 48,
      taxaOcupacao: 0.65,
      precoMedio: 320,
      canalPrincipal: 'Hospedin',
    },
    targetId: 'tgt-003',
    createdAt: '2025-06-08T07:15:00Z',
    updatedAt: '2025-06-15T10:00:00Z',
  },
  {
    id: 'lead-004',
    empresa: 'Pousada do Caminho',
    decisor: 'Fernanda Costa',
    cargo: 'Diretora Comercial',
    email: 'fernanda@pousadadocaminho.com.br',
    whatsapp: '5512999654321',
    setor: 'Hospedagem — Pousada de Luxo',
    socialMedia: {
      instagram: '@pousadadocaminho',
      google: 'Pousada do Caminho — Avaliação 4.9',
    },
    porte: 'medio',
    status: 'pending',
    hook: 'Gap de preço de 22% identificado em feriados — concorrente cobrando R$ 890 vs R$ 690',
    validationScore: 82,
    socialFootprint: {
      instagramSeguidores: 15600,
      googleReviews: 428,
      avgRating: 4.9,
      responseRate: '90%',
    },
    metadata: {
      cnpj: '21.567.890/0001-78',
      quartos: 18,
      taxaOcupacao: 0.82,
      precoMedio: 690,
      canalPrincipal: 'Direto',
    },
    targetId: 'tgt-004',
    createdAt: '2025-06-12T11:00:00Z',
    updatedAt: '2025-06-12T11:00:00Z',
  },
  {
    id: 'lead-005',
    empresa: 'Solar do Vale',
    decisor: 'João Pedro Martins',
    cargo: 'Proprietário',
    email: 'joao@solardovale.com.br',
    whatsapp: '5554999543210',
    setor: 'Hospedagem — Pousada Charme',
    socialMedia: {
      instagram: '@solardovale.canela',
      google: 'Solar do Vale Canela — Avaliação 4.5',
    },
    porte: 'pequeno',
    status: 'contacted',
    hook: 'Taxa de ocupação de 58% em janeiro — média da região é 76%',
    validationScore: 79,
    socialFootprint: {
      instagramSeguidores: 6700,
      googleReviews: 215,
      avgRating: 4.5,
      responseRate: '85%',
    },
    metadata: {
      cnpj: '34.678.901/0001-12',
      quartos: 10,
      taxaOcupacao: 0.58,
      precoMedio: 310,
      canalPrincipal: 'Booking.com',
    },
    targetId: 'tgt-005',
    createdAt: '2025-06-09T14:20:00Z',
    updatedAt: '2025-06-14T09:30:00Z',
  },
  {
    id: 'lead-006',
    empresa: 'Refúgio da Serra',
    decisor: 'Carolina Mendes',
    cargo: 'Gerente Geral',
    email: 'carolina@refugiodaserra.com.br',
    whatsapp: '5524999432109',
    setor: 'Hospedagem — Pousada Ecológica',
    socialMedia: {
      instagram: '@refugiodaserra.paraty',
    },
    porte: 'pequeno',
    status: 'pending',
    hook: 'Sem presença digital — 0 reviews no Google, Instagram com 890 seguidores',
    validationScore: 61,
    socialFootprint: {
      instagramSeguidores: 890,
      googleReviews: 0,
      avgRating: 0,
      responseRate: 'N/A',
    },
    metadata: {
      cnpj: '25.890.123/0001-45',
      quartos: 8,
      taxaOcupacao: 0.45,
      precoMedio: 250,
      canalPrincipal: 'Trivago',
    },
    targetId: 'tgt-006',
    createdAt: '2025-06-13T10:00:00Z',
    updatedAt: '2025-06-13T10:00:00Z',
  },
  {
    id: 'lead-007',
    empresa: 'Pousada Araras',
    decisor: 'Luiz Claudio Ribeiro',
    cargo: 'Proprietário',
    email: 'luiz@pousadaararas.com.br',
    whatsapp: '5588999321098',
    setor: 'Hospedagem — Pousada Praia',
    socialMedia: {
      instagram: '@pousadaararas.jeri',
      google: 'Pousada Araras — Avaliação 4.2',
    },
    porte: 'pequeno',
    status: 'lost',
    hook: 'Estação seca encerrada — reativar contato em setembro',
    validationScore: 55,
    socialFootprint: {
      instagramSeguidores: 3400,
      googleReviews: 98,
      avgRating: 4.2,
      lastPostDate: '2025-04-20',
      responseRate: '60%',
    },
    metadata: {
      cnpj: '08.901.234/0001-67',
      quartos: 6,
      taxaOcupacao: 0.35,
      precoMedio: 280,
      canalPrincipal: 'Airbnb',
    },
    targetId: 'tgt-007',
    createdAt: '2025-06-02T08:00:00Z',
    updatedAt: '2025-06-08T12:00:00Z',
  },
  {
    id: 'lead-008',
    empresa: 'Laguna Beach Lodge',
    decisor: 'Patricia Souza',
    cargo: 'Diretora Comercial',
    email: 'patricia@lagunabeachlodge.com.br',
    whatsapp: '5548999210987',
    setor: 'Hospedagem — Lodge Praia',
    socialMedia: {
      instagram: '@lagunabeachlodge',
      facebook: 'Laguna Beach Lodge Floripa',
      google: 'Laguna Beach Lodge — Avaliação 4.7',
    },
    porte: 'medio',
    status: 'verified',
    hook: 'Revenue loss estimado de R$ 45k/mês por pricing subotimizado em Carnaval',
    validationScore: 91,
    socialFootprint: {
      instagramSeguidores: 19200,
      googleReviews: 634,
      avgRating: 4.7,
      lastPostDate: '2025-06-15',
      responseRate: '93%',
    },
    metadata: {
      cnpj: '12.345.678/0001-90',
      quartos: 22,
      taxaOcupacao: 0.80,
      precoMedio: 520,
      canalPrincipal: 'Booking.com + Direto',
    },
    targetId: 'tgt-008',
    createdAt: '2025-06-07T16:00:00Z',
    updatedAt: '2025-06-15T17:45:00Z',
  },
  {
    id: 'lead-009',
    empresa: 'Pousada Vila do Dengo',
    decisor: 'Roberto Nascimento',
    cargo: 'Proprietário',
    email: 'roberto@viladodengo.com.br',
    whatsapp: '5571999109876',
    setor: 'Hospedagem — Pousada Histórica',
    socialMedia: {
      instagram: '@viladodengo',
      google: 'Pousada Vila do Dengo — Avaliação 4.4',
    },
    porte: 'pequeno',
    status: 'contacted',
    hook: 'IDP de 41 — um dos piores índices de preço em Paraty histórico',
    validationScore: 76,
    socialFootprint: {
      instagramSeguidores: 5100,
      googleReviews: 178,
      avgRating: 4.4,
      responseRate: '80%',
    },
    metadata: {
      cnpj: '37.012.345/0001-23',
      quartos: 9,
      taxaOcupacao: 0.62,
      precoMedio: 270,
      canalPrincipal: 'Hospedin',
    },
    targetId: null,
    createdAt: '2025-06-11T13:00:00Z',
    updatedAt: '2025-06-14T10:30:00Z',
  },
  {
    id: 'lead-010',
    empresa: 'Chalés do Parque',
    decisor: 'Ana Beatriz Lemos',
    cargo: 'Gerente Geral',
    email: 'anabeatriz@chalesdoparque.com.br',
    whatsapp: '5554999098765',
    setor: 'Hospedagem — Chalés',
    socialMedia: {
      instagram: '@chalesdoparque',
      google: 'Chalés do Parque — Avaliação 4.8',
    },
    porte: 'medio',
    status: 'verified',
    hook: 'Ocupação de 88% em inverno mas preço médio 35% abaixo do mercado',
    validationScore: 85,
    socialFootprint: {
      instagramSeguidores: 11200,
      googleReviews: 467,
      avgRating: 4.8,
      lastPostDate: '2025-06-13',
      responseRate: '91%',
    },
    metadata: {
      cnpj: '45.123.456/0001-89',
      quartos: 16,
      taxaOcupacao: 0.88,
      precoMedio: 380,
      canalPrincipal: 'Direto',
    },
    targetId: null,
    createdAt: '2025-06-10T15:45:00Z',
    updatedAt: '2025-06-15T08:20:00Z',
  },
  {
    id: 'lead-011',
    empresa: 'Pousada Convento da Graça',
    decisor: 'Monsenhor Eduardo Farias',
    cargo: 'Proprietário',
    email: 'eduardo@conventodagraca.com.br',
    whatsapp: '5531999987654',
    setor: 'Hospedagem — Pousada Histórica',
    socialMedia: {
      instagram: '@conventodagraca',
      google: 'Pousada Convento da Graça — Avaliação 4.9',
    },
    porte: 'medio',
    status: 'pending',
    hook: 'Patrimônio histórico com 4.9 de avaliação — potencial de premium pricing',
    validationScore: 93,
    socialFootprint: {
      instagramSeguidores: 8400,
      googleReviews: 312,
      avgRating: 4.9,
      lastPostDate: '2025-06-12',
      responseRate: '87%',
    },
    metadata: {
      cnpj: '16.789.123/0001-01',
      quartos: 14,
      taxaOcupacao: 0.74,
      precoMedio: 420,
      canalPrincipal: 'Booking.com',
    },
    targetId: null,
    createdAt: '2025-06-14T09:00:00Z',
    updatedAt: '2025-06-14T09:00:00Z',
  },
  {
    id: 'lead-012',
    empresa: 'Trancoso Bay Villas',
    decisor: 'Isabela Drummond',
    cargo: 'Diretora de Operações',
    email: 'isabela@trancosobayvillas.com.br',
    whatsapp: '5573999876543',
    setor: 'Hospedagem — Villa de Luxo',
    socialMedia: {
      instagram: '@trancosobayvillas',
      google: 'Trancoso Bay Villas — Avaliação 4.6',
    },
    porte: 'grande',
    status: 'contacted',
    hook: 'ADR de R$ 1.200 mas RevPAR 40% abaixo de propriedades similares em Trancoso',
    validationScore: 89,
    socialFootprint: {
      instagramSeguidores: 28700,
      googleReviews: 156,
      avgRating: 4.6,
      lastPostDate: '2025-06-15',
      responseRate: '96%',
    },
    metadata: {
      cnpj: '29.012.345/0001-56',
      quartos: 32,
      taxaOcupacao: 0.55,
      precoMedio: 1200,
      canalPrincipal: 'Direto + Airbnb Luxo',
    },
    targetId: null,
    createdAt: '2025-06-09T11:30:00Z',
    updatedAt: '2025-06-15T12:00:00Z',
  },
  {
    id: 'lead-013',
    empresa: 'Pousada dos Lençóis',
    decisor: 'Francisco Barros',
    cargo: 'Proprietário',
    email: 'francisco@pousadadoslencois.com.br',
    whatsapp: '5586998765432',
    setor: 'Hospedagem — Pousada Ecodesporte',
    socialMedia: {
      instagram: '@pousadadoslencois',
      google: 'Pousada dos Lençóis — Avaliação 4.3',
    },
    porte: 'pequeno',
    status: 'pending',
    hook: 'Destino em alta (+45% buscas Google YoY) mas pricing defasado há 2 anos',
    validationScore: 72,
    socialFootprint: {
      instagramSeguidores: 4300,
      googleReviews: 87,
      avgRating: 4.3,
      lastPostDate: '2025-06-10',
      responseRate: '75%',
    },
    metadata: {
      cnpj: '06.789.456/0001-78',
      quartos: 11,
      taxaOcupacao: 0.68,
      precoMedio: 220,
      canalPrincipal: 'Booking.com',
    },
    targetId: null,
    createdAt: '2025-06-13T14:15:00Z',
    updatedAt: '2025-06-13T14:15:00Z',
  },
  {
    id: 'lead-014',
    empresa: 'Serra Gaúcha Inn',
    decisor: 'Marcos Vinícius da Silva',
    cargo: 'Gerente Geral',
    email: 'marcos@serragauchainn.com.br',
    whatsapp: '5554998765432',
    setor: 'Hospedagem — Inn Boutique',
    socialMedia: {
      instagram: '@serragauchainn',
      facebook: 'Serra Gaúcha Inn',
      google: 'Serra Gaúcha Inn — Avaliação 4.5',
    },
    porte: 'medio',
    status: 'verified',
    hook: 'Sem overbooking mas taxa de no-show de 18% — necessidade de gestão inteligente',
    validationScore: 80,
    socialFootprint: {
      instagramSeguidores: 7600,
      googleReviews: 298,
      avgRating: 4.5,
      lastPostDate: '2025-06-14',
      responseRate: '89%',
    },
    metadata: {
      cnpj: '41.567.890/0001-34',
      quartos: 20,
      taxaOcupacao: 0.71,
      precoMedio: 410,
      canalPrincipal: 'Hospedin + Booking',
    },
    targetId: null,
    createdAt: '2025-06-08T10:30:00Z',
    updatedAt: '2025-06-14T15:20:00Z',
  },
  {
    id: 'lead-015',
    empresa: 'Pousada Raízes',
    decisor: 'Tatiana Oliveira',
    cargo: 'Proprietária',
    email: 'tatiana@pousadaraizes.com.br',
    whatsapp: '5562998654321',
    setor: 'Hospedagem — Pousada Cultural',
    socialMedia: {
      instagram: '@pousadaraizes.bh',
      google: 'Pousada Raízes — Avaliação 4.7',
    },
    porte: 'pequeno',
    status: 'contacted',
    hook: 'Conceito único em BH — review scores indicam potencial de upsell 35%',
    validationScore: 83,
    socialFootprint: {
      instagramSeguidores: 9200,
      googleReviews: 203,
      avgRating: 4.7,
      lastPostDate: '2025-06-13',
      responseRate: '94%',
    },
    metadata: {
      cnpj: '19.234.567/0001-90',
      quartos: 7,
      taxaOcupacao: 0.85,
      precoMedio: 340,
      canalPrincipal: 'Direto',
    },
    targetId: null,
    createdAt: '2025-06-07T08:45:00Z',
    updatedAt: '2025-06-15T11:30:00Z',
  },
  {
    id: 'lead-016',
    empresa: 'Vila Estrela do Mar',
    decisor: 'Paulo César Almeida',
    cargo: 'Proprietário',
    email: 'paulo@vilaestreladomar.com.br',
    whatsapp: '5582997543210',
    setor: 'Hospedagem — Pousada Praia',
    socialMedia: {
      instagram: '@vilaestreladomar',
      google: 'Vila Estrela do Mar — Avaliação 4.1',
    },
    porte: 'pequeno',
    status: 'lost',
    hook: 'Lead respondeu que já usa sistema concorrente — marcar para reativação Q3',
    validationScore: 58,
    socialFootprint: {
      instagramSeguidores: 2800,
      googleReviews: 64,
      avgRating: 4.1,
      responseRate: '70%',
    },
    metadata: {
      cnpj: '33.678.901/0001-12',
      quartos: 5,
      taxaOcupacao: 0.50,
      precoMedio: 190,
      canalPrincipal: 'Airbnb',
    },
    targetId: null,
    createdAt: '2025-06-04T12:00:00Z',
    updatedAt: '2025-06-10T16:00:00Z',
  },
  {
    id: 'lead-017',
    empresa: 'Fazenda Santo Antônio',
    decisor: 'Dra. Regina Cunha',
    cargo: 'Sócia-Administradora',
    email: 'regina@fazendasantoantonio.com.br',
    whatsapp: '5531997654321',
    setor: 'Hospedagem — Turismo Rural',
    socialMedia: {
      instagram: '@fazendasantoantonio',
      google: 'Fazenda Santo Antônio — Avaliação 4.6',
    },
    porte: 'grande',
    status: 'verified',
    hook: 'Fazenda com 3 modalidades de receita — potencial de otimização cross-sell',
    validationScore: 87,
    socialFootprint: {
      instagramSeguidores: 14500,
      googleReviews: 523,
      avgRating: 4.6,
      lastPostDate: '2025-06-15',
      responseRate: '92%',
    },
    metadata: {
      cnpj: '14.890.123/0001-45',
      quartos: 36,
      taxaOcupacao: 0.70,
      precoMedio: 290,
      canalPrincipal: 'Direto + Hospedin',
    },
    targetId: null,
    createdAt: '2025-06-06T09:00:00Z',
    updatedAt: '2025-06-15T14:00:00Z',
  },
  {
    id: 'lead-018',
    empresa: 'Pousada Encantos de Búzios',
    decisor: 'Fernando Motta',
    cargo: 'Diretor Comercial',
    email: 'fernando@encantosdebuzios.com.br',
    whatsapp: '5522996543210',
    setor: 'Hospedagem — Pousada Praia',
    socialMedia: {
      instagram: '@encantosdebuzios',
      google: 'Encantos de Búzios — Avaliação 4.4',
    },
    porte: 'medio',
    status: 'pending',
    hook: 'Localização premium em Rua das Pedras mas preço médio 25% abaixo de vizinhos',
    validationScore: 81,
    socialFootprint: {
      instagramSeguidores: 16800,
      googleReviews: 389,
      avgRating: 4.4,
      lastPostDate: '2025-06-12',
      responseRate: '86%',
    },
    metadata: {
      cnpj: '27.345.678/0001-67',
      quartos: 15,
      taxaOcupacao: 0.76,
      precoMedio: 580,
      canalPrincipal: 'Booking.com',
    },
    targetId: null,
    createdAt: '2025-06-14T11:30:00Z',
    updatedAt: '2025-06-14T11:30:00Z',
  },
  {
    id: 'lead-019',
    empresa: 'Casa de Pedra Inn',
    decisor: 'Helena Vasconcelos',
    cargo: 'Proprietária',
    email: 'helena@casadepedra.com.br',
    whatsapp: '5531995432109',
    setor: 'Hospedagem — Pousada Colonial',
    socialMedia: {
      instagram: '@casadepedra.op',
      google: 'Casa de Pedra Inn — Avaliação 4.8',
    },
    porte: 'pequeno',
    status: 'contacted',
    hook: 'Patrimônio UNESCO ao lado — diárias 40% abaixo do potencial premium',
    validationScore: 90,
    socialFootprint: {
      instagramSeguidores: 7200,
      googleReviews: 267,
      avgRating: 4.8,
      lastPostDate: '2025-06-14',
      responseRate: '91%',
    },
    metadata: {
      cnpj: '32.901.234/0001-78',
      quartos: 8,
      taxaOcupacao: 0.80,
      precoMedio: 350,
      canalPrincipal: 'Direto',
    },
    targetId: null,
    createdAt: '2025-06-10T10:00:00Z',
    updatedAt: '2025-06-15T09:00:00Z',
  },
  {
    id: 'lead-020',
    empresa: 'Pousada Mirante do Vale',
    decisor: 'Carlos Eduardo Pinto',
    cargo: 'Gerente Geral',
    email: 'carlos@mirantedovale.com.br',
    whatsapp: '5535994321098',
    setor: 'Hospedagem — Pousada Vista Panorâmica',
    socialMedia: {
      instagram: '@mirantedovale',
      google: 'Mirante do Vale — Avaliação 4.3',
    },
    porte: 'pequeno',
    status: 'pending',
    hook: 'Vista panorâmica exclusiva mas sem estratégia de revenue management',
    validationScore: 68,
    socialFootprint: {
      instagramSeguidores: 3900,
      googleReviews: 134,
      avgRating: 4.3,
      responseRate: '78%',
    },
    metadata: {
      cnpj: '38.012.345/0001-90',
      quartos: 10,
      taxaOcupacao: 0.60,
      precoMedio: 260,
      canalPrincipal: 'Booking.com',
    },
    targetId: null,
    createdAt: '2025-06-15T08:00:00Z',
    updatedAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'lead-021',
    empresa: 'Pousada Lua e Mar',
    decisor: 'Daniela Ferreira Lima',
    cargo: 'Proprietária',
    email: 'daniela@luaemar.com.br',
    whatsapp: '5588993210987',
    setor: 'Hospedagem — Pousada Praia',
    socialMedia: {
      instagram: '@luaemar.jeri',
      google: 'Pousada Lua e Mar — Avaliação 4.5',
    },
    porte: 'pequeno',
    status: 'verified',
    hook: 'Taxa de retorno de hóspedes de 45% — indica fidelização mas pricing estagnado',
    validationScore: 77,
    socialFootprint: {
      instagramSeguidores: 5800,
      googleReviews: 112,
      avgRating: 4.5,
      lastPostDate: '2025-06-11',
      responseRate: '88%',
    },
    metadata: {
      cnpj: '09.123.456/0001-23',
      quartos: 7,
      taxaOcupacao: 0.73,
      precoMedio: 310,
      canalPrincipal: 'Airbnb + Direto',
    },
    targetId: null,
    createdAt: '2025-06-12T16:30:00Z',
    updatedAt: '2025-06-14T13:00:00Z',
  },
  {
    id: 'lead-022',
    empresa: 'Estalagem das Flores',
    decisor: 'Márcio Tavares',
    cargo: 'Proprietário',
    email: 'marcio@estalagemdasflores.com.br',
    whatsapp: '5548992109876',
    setor: 'Hospedagem — Estalagem',
    socialMedia: {
      instagram: '@estalagemdasflores.floripa',
      google: 'Estalagem das Flores — Avaliação 4.2',
    },
    porte: 'medio',
    status: 'contacted',
    hook: 'Jardim botânico privado — diferencial não monetizado no pricing',
    validationScore: 73,
    socialFootprint: {
      instagramSeguidores: 6100,
      googleReviews: 189,
      avgRating: 4.2,
      responseRate: '82%',
    },
    metadata: {
      cnpj: '43.567.890/0001-12',
      quartos: 14,
      taxaOcupacao: 0.64,
      precoMedio: 350,
      canalPrincipal: 'Hospedin',
    },
    targetId: null,
    createdAt: '2025-06-09T14:00:00Z',
    updatedAt: '2025-06-14T10:45:00Z',
  },
  {
    id: 'lead-023',
    empresa: 'Pousada Raio de Sol',
    decisor: 'Sandra Menezes',
    cargo: 'Diretora Administrativa',
    email: 'sandra@raiodesol.com.br',
    whatsapp: '5562991098765',
    setor: 'Hospedagem — Pousada Urban',
    socialMedia: {
      instagram: '@raiodsol.goiania',
      google: 'Pousada Raio de Sol — Avaliação 4.6',
    },
    porte: 'medio',
    status: 'pending',
    hook: 'Novo conceito de pousada urbana em Goiânia — sem benchmark local definido',
    validationScore: 65,
    socialFootprint: {
      instagramSeguidores: 4200,
      googleReviews: 78,
      avgRating: 4.6,
      lastPostDate: '2025-06-14',
      responseRate: '90%',
    },
    metadata: {
      cnpj: '52.890.123/0001-34',
      quartos: 12,
      taxaOcupacao: 0.57,
      precoMedio: 230,
      canalPrincipal: 'Direto',
    },
    targetId: null,
    createdAt: '2025-06-15T07:30:00Z',
    updatedAt: '2025-06-15T07:30:00Z',
  },
  {
    id: 'lead-024',
    empresa: 'Chalé Serra Verde',
    decisor: 'André Luiz Gonçalves',
    cargo: 'Proprietário',
    email: 'andre@chaleserraverde.com.br',
    whatsapp: '5554990987654',
    setor: 'Hospedagem — Chalés de Montanha',
    socialMedia: {
      instagram: '@chaleserraverde',
      google: 'Chalé Serra Verde — Avaliação 4.7',
    },
    porte: 'pequeno',
    status: 'contacted',
    hook: 'Único chalé com lareira e banheira em Canela — premium diferenciado',
    validationScore: 86,
    socialFootprint: {
      instagramSeguidores: 10100,
      googleReviews: 345,
      avgRating: 4.7,
      lastPostDate: '2025-06-15',
      responseRate: '93%',
    },
    metadata: {
      cnpj: '36.234.567/0001-56',
      quartos: 6,
      taxaOcupacao: 0.84,
      precoMedio: 560,
      canalPrincipal: 'Direto + Booking Premium',
    },
    targetId: null,
    createdAt: '2025-06-08T13:15:00Z',
    updatedAt: '2025-06-15T16:30:00Z',
  },
  {
    id: 'lead-025',
    empresa: 'Pousada Terra Brasil',
    decisor: 'Luciana Andrade',
    cargo: 'Gerente Geral',
    email: 'luciana@terrabrasil.com.br',
    whatsapp: '5571999876543',
    setor: 'Hospedagem — Eco Pousada',
    socialMedia: {
      instagram: '@terrabrasil.pousada',
      google: 'Pousada Terra Brasil — Avaliação 4.4',
    },
    porte: 'medio',
    status: 'verified',
    hook: 'Certificação sustentável não refletida no pricing — gap de 20% vs concorrentes verdes',
    validationScore: 78,
    socialFootprint: {
      instagramSeguidores: 6800,
      googleReviews: 156,
      avgRating: 4.4,
      lastPostDate: '2025-06-13',
      responseRate: '85%',
    },
    metadata: {
      cnpj: '48.901.234/0001-78',
      quartos: 13,
      taxaOcupacao: 0.69,
      precoMedio: 290,
      canalPrincipal: 'Hospedin + Airbnb',
    },
    targetId: null,
    createdAt: '2025-06-11T15:45:00Z',
    updatedAt: '2025-06-15T10:15:00Z',
  },
];

// ---------------------------------------------------------------------------
// Swipe Templates — Modelos de mensagem para prospecção via WhatsApp
// ---------------------------------------------------------------------------
export const mockSwipeTemplates: SwipeTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Abordagem Diagnóstico IDP',
    category: 'prospecção',
    content:
      'Olá {{nome}}! Sou da ZEHLA SmartHotel. Fizemos um diagnóstico gratuito da {{empresa}} e identificamos uma oportunidade de aumento de receita de até {{percentual}}% através de otimização de preços. Posso te enviar o relatório completo? São apenas 3 minutos de leitura.',
    variables: ['nome', 'empresa', 'percentual'],
    successRate: 0.34,
    usageCount: 147,
    isActive: true,
  },
  {
    id: 'tpl-002',
    name: 'Follow-up Pós-Diagnóstico',
    category: 'follow-up',
    content:
      'Oi {{nome}}, tudo bem? Enviei o relatório de diagnóstico da {{empresa}} na semana passada. Vi que vocês têm {{quartos}} quartos com taxa de ocupação de {{taxa}}% — nosso sistema pode ajudar a chegar a {{taxaMeta}}% sem investir em marketing. Quando pode conversar por 15 minutos?',
    variables: ['nome', 'empresa', 'quartos', 'taxa', 'taxaMeta'],
    successRate: 0.28,
    usageCount: 89,
    isActive: true,
  },
  {
    id: 'tpl-003',
    name: 'Conversão com Prova Social',
    category: 'conversão',
    content:
      '{{nome}}, a {{pousadaReferencia}} em {{cidadeReferencia}} aumentou sua receita em R$ {{valor}}/mês em apenas 60 dias com a ZEHLA. A {{empresa}} tem um perfil muito parecido. Posso agendar uma demonstração ao vivo com seu time? Sem compromisso.',
    variables: ['nome', 'pousadaReferencia', 'cidadeReferencia', 'valor', 'empresa'],
    successRate: 0.42,
    usageCount: 56,
    isActive: true,
  },
  {
    id: 'tpl-004',
    name: 'Reativação Pós-Silêncio',
    category: 'reativação',
    content:
      'Olá {{nome}}! Faz alguns meses que conversamos sobre a ZEHLA para a {{empresa}}. Desde então, lançamos novas funcionalidades de inteligência artificial que automatizam 80% do pricing dinâmico. O cenário do mercado mudou — vale a pena conversar novamente?',
    variables: ['nome', 'empresa'],
    successRate: 0.19,
    usageCount: 34,
    isActive: true,
  },
];

// ---------------------------------------------------------------------------
// Campaigns — Campanhas de outreach
// ---------------------------------------------------------------------------
export const mockCampaigns: Campaign[] = [
  {
    id: 'cmp-001',
    name: 'Prospecção Tiradentes + Ouro Preto — Alta Temporada 2025',
    type: 'whatsapp',
    status: 'active',
    targetAudience: 'Pousadas em Tiradentes e Ouro Preto com IDP < 70',
    messageTemplate: 'tpl-001',
    scheduledAt: '2025-06-15T09:00:00Z',
    startedAt: '2025-06-15T09:02:00Z',
    completedAt: null,
    totalSent: 42,
    totalDelivered: 39,
    totalRead: 28,
    totalReplied: 12,
  },
  {
    id: 'cmp-002',
    name: 'Follow-up Serra Gaúcha — Q2 2025',
    type: 'email',
    status: 'completed',
    targetAudience: 'Leads verificados em Gramado e Canela sem resposta ao WhatsApp',
    messageTemplate: 'tpl-002',
    scheduledAt: '2025-06-10T10:00:00Z',
    startedAt: '2025-06-10T10:05:00Z',
    completedAt: '2025-06-12T18:00:00Z',
    totalSent: 18,
    totalDelivered: 17,
    totalRead: 14,
    totalReplied: 7,
  },
];

// ---------------------------------------------------------------------------
// Agent Logs — Registros de execução da Lessie AI
// ---------------------------------------------------------------------------
export const mockAgentLogs: AgentLog[] = [
  {
    id: 'log-001',
    agentId: 'lessie-hunter-v2',
    action: 'hunt_started',
    inputTokens: 340,
    outputTokens: 128,
    latencyMs: 890,
    costUsd: 0.0023,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:00:12Z',
  },
  {
    id: 'log-002',
    agentId: 'lessie-hunter-v2',
    action: 'email_extracted',
    inputTokens: 1890,
    outputTokens: 85,
    latencyMs: 2340,
    costUsd: 0.0112,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:00:45Z',
  },
  {
    id: 'log-003',
    agentId: 'lessie-hunter-v2',
    action: 'whatsapp_validated',
    inputTokens: 520,
    outputTokens: 42,
    latencyMs: 1230,
    costUsd: 0.0031,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:01:18Z',
  },
  {
    id: 'log-004',
    agentId: 'lessie-validator-v1',
    action: 'validation_completed',
    inputTokens: 3200,
    outputTokens: 340,
    latencyMs: 4560,
    costUsd: 0.0214,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:02:30Z',
  },
  {
    id: 'log-005',
    agentId: 'lessie-diagnostico-v1',
    action: 'revenue_diagnosis',
    inputTokens: 5600,
    outputTokens: 1200,
    latencyMs: 8900,
    costUsd: 0.0567,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:05:00Z',
  },
  {
    id: 'log-006',
    agentId: 'lessie-hunter-v2',
    action: 'social_footprint_scraped',
    inputTokens: 2100,
    outputTokens: 580,
    latencyMs: 6780,
    costUsd: 0.0345,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:06:45Z',
  },
  {
    id: 'log-007',
    agentId: 'lessie-router-v1',
    action: 'model_routing',
    inputTokens: 180,
    outputTokens: 95,
    latencyMs: 420,
    costUsd: 0.0012,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:07:00Z',
  },
  {
    id: 'log-008',
    agentId: 'lessie-hunter-v2',
    action: 'email_extracted',
    inputTokens: 1650,
    outputTokens: 72,
    latencyMs: 3100,
    costUsd: 0.0098,
    status: 'failed',
    errorMsg: 'Timeout ao acessar página de contato — sem fallback disponível para DOM malformado',
    createdAt: '2025-06-15T09:08:12Z',
  },
  {
    id: 'log-009',
    agentId: 'lessie-validator-v1',
    action: 'lead_scored',
    inputTokens: 2400,
    outputTokens: 190,
    latencyMs: 3200,
    costUsd: 0.0167,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:09:30Z',
  },
  {
    id: 'log-010',
    agentId: 'lessie-campaign-v1',
    action: 'bulk_whatsapp_queued',
    inputTokens: 890,
    outputTokens: 210,
    latencyMs: 1560,
    costUsd: 0.0067,
    status: 'success',
    errorMsg: '',
    createdAt: '2025-06-15T09:10:00Z',
  },
];

// ---------------------------------------------------------------------------
// Router Providers — ZaosNeuroRouter com Thompson Sampling
// ---------------------------------------------------------------------------
export const mockRouterProviders: RouterProvider[] = [
  {
    id: 'prv-001',
    provider: 'OpenRouter',
    modelName: 'GPT-4o',
    tier: 'tier-1',
    alpha: 14.0,
    beta: 3.0,
    circuitStatus: 'closed',
    lastFailureAt: null,
    failureCount: 0,
    successCount: 1847,
    avgLatencyMs: 1200,
    costPer1kInput: 2.5,
    costPer1kOutput: 10.0,
    isActive: true,
    supportsJson: true,
    supportsTools: true,
  },
  {
    id: 'prv-002',
    provider: 'Anthropic',
    modelName: 'Claude 3.5 Sonnet',
    tier: 'tier-1',
    alpha: 12.5,
    beta: 2.5,
    circuitStatus: 'closed',
    lastFailureAt: '2025-06-14T22:15:00Z',
    failureCount: 2,
    successCount: 1623,
    avgLatencyMs: 1450,
    costPer1kInput: 3.0,
    costPer1kOutput: 15.0,
    isActive: true,
    supportsJson: true,
    supportsTools: true,
  },
  {
    id: 'prv-003',
    provider: 'Ollama',
    modelName: 'Llama 3 8B',
    tier: 'tier-3',
    alpha: 8.0,
    beta: 7.0,
    circuitStatus: 'closed',
    lastFailureAt: null,
    failureCount: 0,
    successCount: 942,
    avgLatencyMs: 340,
    costPer1kInput: 0.0,
    costPer1kOutput: 0.0,
    isActive: true,
    supportsJson: true,
    supportsTools: false,
  },
  {
    id: 'prv-004',
    provider: 'Groq',
    modelName: 'Llama 3.1 70B',
    tier: 'tier-2',
    alpha: 10.0,
    beta: 4.5,
    circuitStatus: 'half_open',
    lastFailureAt: '2025-06-15T07:45:00Z',
    failureCount: 5,
    successCount: 789,
    avgLatencyMs: 280,
    costPer1kInput: 0.59,
    costPer1kOutput: 0.79,
    isActive: true,
    supportsJson: true,
    supportsTools: true,
  },
  {
    id: 'prv-005',
    provider: 'Gemini',
    modelName: '1.5 Flash',
    tier: 'tier-2',
    alpha: 9.5,
    beta: 5.0,
    circuitStatus: 'closed',
    lastFailureAt: null,
    failureCount: 1,
    successCount: 1102,
    avgLatencyMs: 580,
    costPer1kInput: 0.075,
    costPer1kOutput: 0.3,
    isActive: true,
    supportsJson: true,
    supportsTools: true,
  },
];

// ---------------------------------------------------------------------------
// Budget Guard — Estado atual do guardião de orçamento
// ---------------------------------------------------------------------------
export const mockBudgetGuard: BudgetGuardState = {
  id: 'budget-2025-06-15',
  date: '2025-06-15',
  dailySpendUsd: 1.87,
  dailyBudgetUsd: 5.0,
  monthlySpendUsd: 34.52,
  monthlyBudgetUsd: 150.0,
  criticalLevel: 'nominal',
};