export const SEED_SWIPES = [
  { title: "Saudacao WhatsApp Padrao", content: "Ola {{NOME}}! Sou a IA da {{POUSADA}}. Vi sua mensagem e vou te ajudar agora mesmo!", channel: "whatsapp", category: "saudacao", tone: "casual", tier: "universal", painType: null, tags: ["primeiro contato", "boas-vindas"] },
  { title: "Saudacao Concierge Premium", content: "Bom dia, {{NOME}}. Aqui e a {{POUSADA}}. Fico feliz pelo seu interesse. Como posso ajudar?", channel: "whatsapp", category: "saudacao", tone: "concierge", tier: "pro", painType: null, tags: ["premium", "formal"] },
  { title: "Resposta a Preco - Suite Simples", content: "{{NOME}}, nossas suites variam de R$ {{PRECO_MIN}} a R$ {{PRECO_MAX}} por noite, incluindo cafe da manha!", channel: "whatsapp", category: "preco", tone: "casual", tier: "lite", painType: "financeiro", tags: ["preco", "valor"] },
  { title: "Resposta a Preco - Com Desconto", content: "{{NOME}}, para reservas ate sexta, a {{POUSADA}} esta com 15% de desconto! Suite {{SUITE_NOME}} por R$ {{PRECO_DESCONTO}}/noite.", channel: "whatsapp", category: "preco", tone: "urgente", tier: "pro", painType: "financeiro", tags: ["desconto", "urgencia"] },
  { title: "Disponibilidade - Temos Vagas!", content: "Otima noticia, {{NOME}}! Temos vagas para {{DATA_CHECKIN}} a {{DATA_CHECKOUT}} por R$ {{PRECO}}/noite. Quer reservar?", channel: "whatsapp", category: "disponibilidade", tone: "casual", tier: "universal", painType: "ocupacao", tags: ["vagas", "disponibilidade"] },
  { title: "Follow-up 3 dias", content: "Oi {{NOME}}! Passando para saber se ainda pensa na {{POUSADA}}. Datas limitadas para o periodo!", channel: "whatsapp", category: "followup", tone: "casual", tier: "lite", painType: null, tags: ["followup", "lembrete"] },
  { title: "Follow-up 7 dias - Urgencia", content: "{{NOME}}, as datas {{DATA_INICIO}} a {{DATA_FIM}} estao sendo procuradas. Restam 3 suites!", channel: "whatsapp", category: "followup", tone: "urgente", tier: "pro", painType: "ocupacao", tags: ["urgencia", "escassez"] },
  { title: "Recuperacao - Reserva Abandonada", content: "{{NOME}}, vi que comecou a reserva mas nao finalizou. Posso ajudar com PIX mais simples?", channel: "whatsapp", category: "recuperacao", tone: "empatico", tier: "universal", painType: "financeiro", tags: ["abandono", "recuperacao"] },
  { title: "Objecao - E Muito Caro", content: "{{NOME}}, entendo. Mas na {{POUSADA}} voce tem cafe artesanal, piscina, estacionamento gratis e atendimento 24h. Quer um orcamento personalizado?", channel: "whatsapp", category: "objecao", tone: "executivo", tier: "max", painType: "financeiro", tags: ["objecao", "valor"] },
  { title: "Encerramento - Agradecimento", content: "{{NOME}}, obrigado pelo contato! Estamos a disposicao. Volte sempre a {{POUSADA}}!", channel: "whatsapp", category: "encerramento", tone: "concierge", tier: "universal", painType: null, tags: ["encerramento", "agradecimento"] },
];
