const XLSX = require('xlsx');
const path = require('path');
const os = require('os');

const filePath = path.join(os.homedir(), 'Downloads', 'POUSADAS_SAQUAREMA(1).xlsx');

const leads = [
  // LOTE 1 (Anterior)
  { "#": 1, "Pousada": "Pousada das Garças", "E-mail": "contato@pousadagarcas.com.br", "Whatsapp": "552226512116", "Qtd Quartos": 15, "Local / Praia": "Itaúna", "Cidade": "Saquarema", "UF": "RJ", "Valores Estimados": "R$ 450 - R$ 800", "Qualificação": "Alto Padrão - Próximo ao Pico", "Validação": "VALIDADO", "Comportamento de Compra": "Dono presente, valoriza exclusividade", "Sinais de Intenção": "Alta demanda no surf", "Redes Sociais": "instagram.com/pousadagarcas", "Site": "pousadagarcas.com.br", "Telefone": "2226512116", "Score Qual.": 95, "Score Valid.": 100 },
  { "#": 2, "Pousada": "Solar de Itaúna", "E-mail": "reservas@solardeitauna.com.br", "Whatsapp": "5522998346471", "Qtd Quartos": 12, "Local / Praia": "Itaúna", "Cidade": "Saquarema", "UF": "RJ", "Valores Estimados": "R$ 400 - R$ 700", "Qualificação": "Médio-Alto Padrão - Familiar", "Validação": "VALIDADO", "Comportamento de Compra": "Focado em reservas diretas", "Sinais de Intenção": "Investindo em marketing local", "Redes Sociais": "instagram.com/solardeitauna", "Site": "solardeitauna.com.br", "Telefone": "22998346471", "Score Qual.": 88, "Score Valid.": 100 },
  { "#": 3, "Pousada": "Laje de Itaúna (Hotel e Spa)", "E-mail": "laje.itauna@gmail.com", "Whatsapp": "552226512389", "Qtd Quartos": 20, "Local / Praia": "Itaúna", "Cidade": "Saquarema", "UF": "RJ", "Valores Estimados": "R$ 600 - R$ 1200", "Qualificação": "Luxo - Spa e Conforto", "Validação": "VALIDADO", "Comportamento de Compra": "Público exigente, ticket alto", "Sinais de Intenção": "Busca automação de serviços", "Redes Sociais": "instagram.com/lajeitauna", "Site": "pousadasitauna.com.br", "Telefone": "2226512389", "Score Qual.": 98, "Score Valid.": 90 },
  { "#": 4, "Pousada": "Paraíso de Itaúna", "E-mail": "contato@pousadaparaisodeitauna.com", "Whatsapp": "5521988909602", "Qtd Quartos": 10, "Local / Praia": "Itaúna", "Cidade": "Saquarema", "UF": "RJ", "Valores Estimados": "R$ 350 - R$ 600", "Qualificação": "Pé na areia - Surf oriented", "Validação": "AGUARDANDO", "Comportamento de Compra": "Espírito jovem, surfistas", "Sinais de Intenção": "Gargalo no atendimento WhatsApp", "Redes Sociais": "instagram.com/paraisodeitauna", "Site": "pousadaparaisodeitauna.com", "Telefone": "21988909602", "Score Qual.": 85, "Score Valid.": 70 },
  { "#": 5, "Pousada": "Castelhana Sudoeste", "E-mail": "reservas@castelhanasudoeste.com.br", "Whatsapp": "552127193530", "Qtd Quartos": 8, "Local / Praia": "Itaúna", "Cidade": "Saquarema", "UF": "RJ", "Valores Estimados": "R$ 500 - R$ 900", "Qualificação": "Exclusiva - Design Moderno", "Validação": "PROSPECT", "Comportamento de Compra": "Foco em experiência e design", "Sinais de Intenção": "Pouca presença digital agressiva", "Redes Sociais": "instagram.com/castelhanasudoeste", "Site": "castelhanasudoeste.com.br", "Telefone": "2127193530", "Score Qual.": 92, "Score Valid.": 60 },
  
  // LOTE 2 (Novos 10 Leads)
  { 
    "#": 6, 
    "Pousada": "Hotel Maasai", 
    "E-mail": "maasai@maasai.com.br", 
    "Whatsapp": "5522997422411", 
    "Qtd Quartos": 25, 
    "Local / Praia": "Itaúna", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 700 - R$ 1500", 
    "Qualificação": "Alto Padrão - Estilo Africano", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Busca tecnologia de ponta", 
    "Sinais de Intenção": "Alta taxa de ocupação", 
    "Redes Sociais": "instagram.com/hotelmaasai", 
    "Site": "hotelmaasai.com.br", 
    "Telefone": "22997422411", 
    "Score Qual.": 100, 
    "Score Valid.": 100 
  },
  { 
    "#": 7, 
    "Pousada": "V!ver Pousada", 
    "E-mail": "reservas@pousadaviver.com.br", 
    "Whatsapp": "5522997343753", 
    "Qtd Quartos": 14, 
    "Local / Praia": "Itaúna", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 500 - R$ 900", 
    "Qualificação": "Médio-Alto Padrão - Wellness", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Foco em bem-estar e retiros", 
    "Sinais de Intenção": "Interesse em automação de reservas", 
    "Redes Sociais": "instagram.com/pousadaviver", 
    "Site": "pousadaviver.com.br", 
    "Telefone": "22997343753", 
    "Score Qual.": 94, 
    "Score Valid.": 100 
  },
  { 
    "#": 8, 
    "Pousada": "Pousada da Tia Lúcia (Odara)", 
    "E-mail": "pousadadatialuciasaquarema@gmail.com", 
    "Whatsapp": "5522997203330", 
    "Qtd Quartos": 18, 
    "Local / Praia": "Boqueirão", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 300 - R$ 550", 
    "Qualificação": "Tradição - Familiar", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Gestão tradicional, busca renovação", 
    "Sinais de Intenção": "Migração de marca recente", 
    "Redes Sociais": "instagram.com/pousadadatialucia", 
    "Site": "pousadadatialucia.com", 
    "Telefone": "22997203330", 
    "Score Qual.": 82, 
    "Score Valid.": 100 
  },
  { 
    "#": 9, 
    "Pousada": "Pousada Santa Monica", 
    "E-mail": "reservas@pousadasantamonica.com.br", 
    "Whatsapp": "5522997559300", 
    "Qtd Quartos": 30, 
    "Local / Praia": "Boqueirão", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 450 - R$ 750", 
    "Qualificação": "Grande Porte - Eventos", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Foco em ocupação massiva", 
    "Sinais de Intenção": "Busca escala no marketing", 
    "Redes Sociais": "instagram.com/pousadasantamonica", 
    "Site": "pousadasantamonica.com.br", 
    "Telefone": "22997559300", 
    "Score Qual.": 89, 
    "Score Valid.": 100 
  },
  { 
    "#": 10, 
    "Pousada": "Pousada Solar Tropical", 
    "E-mail": "solartropicalsaquarema@gmail.com", 
    "Whatsapp": "5521981824468", 
    "Qtd Quartos": 12, 
    "Local / Praia": "Boqueirão", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 350 - R$ 600", 
    "Qualificação": "Conforto - Custo Benefício", 
    "Validação": "PROSPECT", 
    "Comportamento de Compra": "Dono opera o WhatsApp", 
    "Sinais de Intenção": "Sobrecarga de atendimento", 
    "Redes Sociais": "instagram.com/solartropical", 
    "Site": "solartropicalsaquarema.com.br", 
    "Telefone": "21981824468", 
    "Score Qual.": 78, 
    "Score Valid.": 80 
  },
  { 
    "#": 11, 
    "Pousada": "Pousada Pratagy", 
    "E-mail": "contato@pousadapratagy.com.br", 
    "Whatsapp": "552226519109", 
    "Qtd Quartos": 16, 
    "Local / Praia": "Boqueirão", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 400 - R$ 650", 
    "Qualificação": "Tranquilidade - Próximo à Lagoa", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Perfil conservador", 
    "Sinais de Intenção": "Baixa conversão no site", 
    "Redes Sociais": "instagram.com/pousadapratagy", 
    "Site": "pousadapratagy.com.br", 
    "Telefone": "2226519109", 
    "Score Qual.": 84, 
    "Score Valid.": 90 
  },
  { 
    "#": 12, 
    "Pousada": "Aloha Itaúna", 
    "E-mail": "alohaitauna@gmail.com", 
    "Whatsapp": "552226519486", 
    "Qtd Quartos": 10, 
    "Local / Praia": "Itaúna", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 300 - R$ 500", 
    "Qualificação": "Surf Style - Econômica Confort", 
    "Validação": "PROSPECT", 
    "Comportamento de Compra": "Comunidade surf", 
    "Sinais de Intenção": "Forte presença em grupos WA", 
    "Redes Sociais": "instagram.com/alohaitauna", 
    "Site": "alohaitauna.com.br", 
    "Telefone": "2226519486", 
    "Score Qual.": 75, 
    "Score Valid.": 70 
  },
  { 
    "#": 13, 
    "Pousada": "Pousada Ondas de Itaúna", 
    "E-mail": "ondasdeitauna@hotmail.com", 
    "Whatsapp": "552226517883", 
    "Qtd Quartos": 14, 
    "Local / Praia": "Itaúna", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 350 - R$ 600", 
    "Qualificação": "Surf & Sun - Tradicional", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Fiel aos hóspedes antigos", 
    "Sinais de Intenção": "Dificuldade com novos canais", 
    "Redes Sociais": "instagram.com/ondasdeitauna", 
    "Site": "ondasdeitauna.com.br", 
    "Telefone": "2226517883", 
    "Score Qual.": 80, 
    "Score Valid.": 100 
  },
  { 
    "#": 14, 
    "Pousada": "Itaúna Beach", 
    "E-mail": "contato@itaunabeach.com.br", 
    "Whatsapp": "5522992030165", 
    "Qtd Quartos": 22, 
    "Local / Praia": "Itaúna", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 500 - R$ 850", 
    "Qualificação": "Médio-Alto - Frente Mar", 
    "Validação": "VALIDADO", 
    "Comportamento de Compra": "Arrojado, investe em anúncios", 
    "Sinais de Intenção": "Busca CRM para WhatsApp", 
    "Redes Sociais": "instagram.com/itaunabeach", 
    "Site": "itaunabeach.com.br", 
    "Telefone": "22992030165", 
    "Score Qual.": 91, 
    "Score Valid.": 100 
  },
  { 
    "#": 15, 
    "Pousada": "Pousada das Conchas", 
    "E-mail": "pousadadasconchassaquarema@gmail.com", 
    "Whatsapp": "552226511403", 
    "Qtd Quartos": 12, 
    "Local / Praia": "Vila", 
    "Cidade": "Saquarema", 
    "UF": "RJ", 
    "Valores Estimados": "R$ 300 - R$ 500", 
    "Qualificação": "Centro - Histórico", 
    "Validação": "PROSPECT", 
    "Comportamento de Compra": "Hóspedes de fim de semana", 
    "Sinais de Intenção": "Pouca automação no checkout", 
    "Redes Sociais": "instagram.com/pousadadasconchas", 
    "Site": "pousadadasconchas.com.br", 
    "Telefone": "2226511403", 
    "Score Qual.": 76, 
    "Score Valid.": 80 
  }
];

const ws = XLSX.utils.json_to_sheet(leads);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Leads");

XLSX.writeFile(wb, filePath);
console.log(`Planilha ATUALIZADA com 15 leads em: ${filePath}`);
