name: CI
on:
  push:
      branches: [ principal ]
      jobs:
        build:
            runs-on: ubuntu-latest
                steps:
                      - uses: actions/checkout@v4
                            - uses: pnpm/action-setup@v3
                                    with:
                                              version: 9
                                                    - run: |
                                                              cd zehla-backend
                                                                        pnpm install --no-frozen-lockfile
                                                                                  pnpm test
                                                                                  
